### ISSUE TITLE
get the gosunds working using tuya stuff

### ISSUE THREAD

**Issue by sophiathekitty** [sophiathekitty/NullLights#9]
### Description
I would like to add support for Tuya lights in my light automation project. This will allow me to integrate Tuya devices and control them through my existing system. To achieve this, I need to make the necessary modifications to the project and ensure that the Tuya lights can be stored and accessed in the database.

### Goals
see if i can get a device switched over to the SmartLife app or whatever and see if i can get the [tiny tuya](https://github.com/jasonacox/tinytuya#readme) working. and then see if i can get it all integrated into my stuff. so i can control the gosunds with my interface and have automations do stuff with them.

### Tasks
- [x] Research the [tiny tuya](https://github.com/jasonacox/tinytuya#readme) library and its capabilities.
- [x] Get the cloud stuff setup and connected with my Smart Life app.
- [x] Write Model for Tuya devices.
- [x] Modules and API for syncing between devices.
- [x] python script to control Tuya lights using TinyTuya.
- [x] Test the integration with Tuya lights to ensure proper functionality.
- [x] Add Tuya support to RoomLightsGroup.

### Additional Information
- Relevant documentation: [tiny tuya](https://github.com/jasonacox/tinytuya#readme)
### Expected Outcome
After implementing this feature, I should be able to add and control Tuya lights within my light automation project. The Tuya devices should be properly stored in the database and accessible through the TinyTuya library.

**Comment by sophiathekitty** [comment]
looks like everything is working. at least good enough to call this done.
